version: '3.7'
networks:
  producao-local:
    driver: bridge
services:
    mongodb:
      image: mongo
      container_name: mongodb
      networks:
        - producao-local
      ports:
        - 27017:27017
    
    mapfood:
        build:
          dockerfile: ./target/tomcat.dockerfile
          context: .
        image: tomcat:latest
        container_name: mapfood
        networks:
          - producao-local
        ports:
          - "8080:8080"
        depends_on: 
          - "mongodb"     